# Generated by Django 2.2.4 on 2019-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('U_idno', models.AutoField(primary_key=True, serialize=False)),
                ('U_name', models.CharField(max_length=50)),
                ('U_contact', models.IntegerField()),
                ('U_email', models.EmailField(max_length=254)),
                ('U_password', models.CharField(max_length=10)),
                ('U_status', models.CharField(max_length=10)),
                ('U_DoR', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
