# Generated by Django 2.2.4 on 2019-12-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='U_contact',
            field=models.IntegerField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='U_email',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
    ]
