# Generated by Django 2.2.4 on 2020-01-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191211_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('bprice', models.FloatField()),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='product/')),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserRegistration')),
            ],
        ),
    ]
